[Settings]
ID = "pep8org"

[build]
  base    = "/"
  publish = "/"

[[headers]]
  for = "/*"
  [headers.values]
    Feature-Policy = """
        accelerometer 'none';
        camera 'none';
        geolocation 'none';
        gyroscope 'none';
        magnetometer 'none';
        microphone 'none';
        payment 'none';
        usb 'none'
        """
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000; preload" # one month for now
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
